version: "3"

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: manitoupetidb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./manitoupetidb.sql:/docker-entrypoint-initdb.d/manitoupetidb.sql
    networks:
      - internalnet
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u user --password=password",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      DB_HOST: "mysqldb"
      DB_USER: "root"
      DB_PORT: 3306
      DB_PASSWORD: "password"
      DB_NAME: "manitoupetidb"
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - internalnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

networks:
  internalnet:
    driver: bridge
